// <auto-generated />
using BitcoinWalletWatcher.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BitcoinWalletWatcher.Migrations
{
    [DbContext(typeof(MonitorContext))]
    partial class MonitorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("BitcoinWalletWatcher.Data.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<decimal>("CurrentBalanceBTC");

                    b.Property<DateTime>("LastBalanceScrapedAt");

                    b.Property<decimal>("MaxBalanceBTC");

                    b.Property<string>("Notes");

                    b.HasKey("WalletId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("BitcoinWalletWatcher.Data.WalletBalance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("BalanceBTC");

                    b.Property<DateTime>("ScrapedAt");

                    b.Property<int>("WalletId");

                    b.HasKey("BalanceId");

                    b.ToTable("WalletBalances");
                });
#pragma warning restore 612, 618
        }
    }
}
